### ISSUE TITLE
Error in big.matrix

### ISSUE THREAD

**Issue by Wangchangsh** [xiaolei-lab/rMVP#40]
dear Liu，I got a problem in using ‘FarmCPU’ model. 
 MVP(phe=pheno,geno=geno,map=map,method=c('FarmCPU'))
Input data has 159 individuals, 1565878 markers 
|------------------------GWAS Start------------------------| 
FarmCPU Start... 
Current loop: 1 out of maximum of 10 
seqQTN: 
NULL 
scanning... 
number of covariates in current loop is: 
0 

|>                                                  1.00%
|->                                                 2.00%
|->                                                 3.00%
|-->                                                4.00%
|-->                                                5.00%
|--->                                               6.00%
|--->                                               7.00%
|---->                                              8.00%
|---->                                              9.00%
|----->                                             10.00%
|----->                                             11.00%
|------>                                            12.00%
|------>                                            13.00%
|------->                                           14.00%
|------->                                           15.00%
|-------->                                          16.00%
|-------->                                          17.00%
|--------->                                         18.00%
|--------->                                         19.00%
|---------->                                        20.00%
|---------->                                        21.00%
|----------->                                       22.00%
|----------->                                       23.00%
|------------>                                      24.00%
|------------>                                      25.00%
|------------->                                     26.00%
|------------->                                     27.00%
|-------------->                                    28.00%
|-------------->                                    29.00%
|--------------->                                   30.00%
|--------------->                                   31.00%
|---------------->                                  32.00%
|---------------->                                  33.00%
|----------------->                                 34.00%
|----------------->                                 35.00%
|------------------>                                36.00%
|------------------>                                37.00%
|------------------->                               38.00%
|------------------->                               39.00%
|-------------------->                              40.00%
|-------------------->                              41.00%
|--------------------->                             42.00%
|--------------------->                             43.00%
|---------------------->                            44.00%
|---------------------->                            45.00%
|----------------------->                           46.00%
|----------------------->                           47.00%
|------------------------>                          48.00%
|------------------------>                          49.00%
|------------------------->                         50.00%
|------------------------->                         51.00%
|-------------------------->                        52.00%
|-------------------------->                        53.00%
|--------------------------->                       54.00%
|--------------------------->                       55.00%
|---------------------------->                      56.00%
|---------------------------->                      57.00%
|----------------------------->                     58.00%
|----------------------------->                     59.00%
|------------------------------>                    60.00%
|------------------------------>                    61.00%
|------------------------------->                   62.00%
|------------------------------->                   63.00%
|-------------------------------->                  64.00%
|-------------------------------->                  65.00%
|--------------------------------->                 66.00%
|--------------------------------->                 67.00%
|---------------------------------->                68.00%
|---------------------------------->                69.00%
|----------------------------------->               70.00%
|----------------------------------->               71.00%
|------------------------------------>              72.00%
|------------------------------------>              73.00%
|------------------------------------->             74.00%
|------------------------------------->             75.00%
|-------------------------------------->            76.00%
|-------------------------------------->            77.00%
|--------------------------------------->           78.00%
|--------------------------------------->           79.00%
|---------------------------------------->          80.00%
|---------------------------------------->          81.00%
|----------------------------------------->         82.00%
|----------------------------------------->         83.00%
|------------------------------------------>        84.00%
|------------------------------------------>        85.00%
|------------------------------------------->       86.00%
|------------------------------------------->       87.00%
|-------------------------------------------->      88.00%
|-------------------------------------------->      89.00%
|--------------------------------------------->     90.00%
|--------------------------------------------->     91.00%
|---------------------------------------------->    92.00%
|---------------------------------------------->    93.00%
|----------------------------------------------->   94.00%
|----------------------------------------------->   95.00%
|------------------------------------------------>  96.00%
|------------------------------------------------>  97.00%
|-------------------------------------------------> 98.00%
|-------------------------------------------------> 99.00%
|-------------------------------------------------->100.00%
Current loop: 2 out of maximum of 10 
Optimizing Pseudo QTNs... 
Error in big.matrix(nrow = length(rows), ncol = length(cols), type = type,  : 
  A big.matrix must have at least one row and one column
此外: Warning messages:
1: In FarmCPU.Specify(GI = GM, GP = GP, bin.size = b, inclosure.size = s) :
  强制改变过程中产生了NA
2: In ID.GP/bin.size : 长的对象长度不是短的对象长度的整倍数
3: In FarmCPU.Specify(GI = GM, GP = GP, bin.size = b, inclosure.size = s) :
  强制改变过程中产生了NA
4: In FarmCPU.Specify(GI = GM, GP = GP, bin.size = b, inclosure.size = s) :
  强制改变过程中产生了NA
5: In FarmCPU.Specify(GI = GM, GP = GP, bin.size = b, inclosure.size = s) :
  强制改变过程中产生了NA
I'm a beginner and I don't konw how to deal with it, please help me.

**Comment by YinLiLin** [comment]
Hi,

This issue usually happen when the chromosomes are assigned with non-numerical strings, which is not acceptable for FarmCPU. Please double check your map file, and if this is the case, please replace your chromosome names with digital value prior to running rMVP.
Additionally, this bug has been fixed at version 0.99.15 which will be released on GitHub and R CRAN in the coming days.

Lilin

**Comment by Wangchangsh** [comment]
> Hi,
> 
> This issue usually happen when the chromosomes are assigned with non-numerical strings, which is not acceptable for FarmCPU. Please double check your map file, and if this is the case, please replace your chromosome names with digital value prior to running rMVP.
> Additionally, this bug has been fixed at version 0.99.15 which will be released on GitHub and R CRAN in the coming days.
> 
> Lilin

Thanks for your reply and I make it.

**Comment by tahill** [comment]
Hi,

I am getting this exact error message when running FarmCPU. GLM and MLM run fine. I converted my chrom and pos columns in the map file to numeric but still get this message.

**Comment by Wangchangsh** [comment]
> Hi,
> 
> I am getting this exact error message when running FarmCPU. GLM and MLM run fine. I converted my chrom and pos columns in the map file to numeric but still get this message.

this bug has been fixed at version 0.99.15, maybe you need update and try.
